services:
  api:
    image: ghcr.io/nar-oah/degrading-anxiety/api:latest
    container_name: degrading-anxiety-api
    restart: always
    networks:
      - traefik
      - backend
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.degrading-anxiety.rule=Host(`aws.naroah.top`) && PathPrefix(`/degrading-anxiety`)"
      - "traefik.http.routers.degrading-anxiety.entrypoints=websecure"
      - "traefik.http.routers.degrading-anxiety.tls.certresolver=letsencrypt"
      - "traefik.http.services.degrading-anxiety.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.degrading-anxiety-strip.stripprefix.prefixes=/degrading-anxiety"
      - "traefik.http.routers.degrading-anxiety.middlewares=degrading-anxiety-strip"

  schedule:
    image: ghcr.io/nar-oah/degrading-anxiety/schedule:latest
    container_name: degrading-anxiety-schedule
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - radicale-auth:/auth
    depends_on:
      radicale:
        condition: service_healthy

  radicale:
    image: ghcr.io/nar-oah/degrading-anxiety/radicale:latest
    container_name: degrading-anxiety-radicale
    restart: unless-stopped
    init: true

    security_opt:
      - no-new-privileges:true

    networks:
      - traefik
      - backend

    volumes:
      - radicale-auth:/auth
      - radicale-data:/var/lib/radicale

    healthcheck:
      test:
        - CMD
        - /app/bin/python
        - -c
        - >
          import socket;
          connection = socket.create_connection(("127.0.0.1", 5232), 2);
          connection.close()
      interval: 10s
      timeout: 3s
      retries: 6
      start_period: 10s

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.degrading-anxiety-radicale.rule=Host(`aws.naroah.top`) && PathPrefix(`/degrading-anxiety/radicale`)"
      - "traefik.http.routers.degrading-anxiety-radicale.priority=100"
      - "traefik.http.routers.degrading-anxiety-radicale.entrypoints=websecure"
      - "traefik.http.routers.degrading-anxiety-radicale.tls=true"
      - "traefik.http.routers.degrading-anxiety-radicale.tls.certresolver=letsencrypt"

      - "traefik.http.routers.degrading-anxiety-radicale.service=degrading-anxiety-radicale"
      - "traefik.http.services.degrading-anxiety-radicale.loadbalancer.server.port=5232"

      - "traefik.http.middlewares.degrading-anxiety-radicale-strip.stripprefix.prefixes=/degrading-anxiety/radicale"
      - "traefik.http.middlewares.degrading-anxiety-radicale-script.headers.customrequestheaders.X-Script-Name=/degrading-anxiety/radicale"
      - "traefik.http.routers.degrading-anxiety-radicale.middlewares=degrading-anxiety-radicale-strip,degrading-anxiety-radicale-script"

volumes:
  radicale-auth:
    name: degrading-anxiety-radicale-auth

  radicale-data:
    name: degrading-anxiety-radicale-data

networks:
  traefik:
    external: true

  backend:
    external: true
